In [1]:
#numpy: 
#======

#numpy is a package which can handle large set of data in the form of arrays and matrices.
#we can use numpy to handle multi dimensional arrays.
#importing numpy on our notebook

import numpy as np#np is a alias names, now instead of using numpy everywhere in our code, we can use np.
#we can define any names as alias names.
#checing any package version
print(np.__version__)

l=(10,20,30,40,50)
print(type(l))
print('converting list to array')
l=np.array(l)
print(type(l))
print(l)

2.2.1
<class 'tuple'>
converting list to array
<class 'numpy.ndarray'>
[10 20 30 40 50]


In [2]:
#arrange(): It is a predefined it is used to get an array with the given from and to values.
#example
a=np.arange(1000)
print(a)
a=np.arange(10,500)
print("<==================================================================================>")
print(a)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [3]:
a=np.arange(0,3.5)
a

array([0., 1., 2., 3.])

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
np.arange(-10,50)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
        42,  43,  44,  45,  46,  47,  48,  49])

In [8]:
#always the left side value is lessthan the right side value. 
#if we pass the value greater than the right side then we will get empty array
np.arange(10,5)

array([], dtype=int64)

In [9]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [10]:
np.arange(10,10)#no range between 10 to 10

array([], dtype=int64)

In [11]:
np.arange(1,5,2)#here 2 is steper count

array([1, 3])

In [12]:
np.arange(10,50,10)

array([10, 20, 30, 40])

In [13]:
#arange() accepts maximum three parameters only, if we try to pass morethan three we will get error.
np.arange(10,50,2,5)

TypeError: Cannot interpret '5' as a data type

In [14]:
#zeros(): it is used to get the arrays filled with zeros
#example

a=np.zeros(10)
print(a)#by default it will gives the float values.
#if we don't want the float values then we have to perform the hyperparameter tunning.
print(np.zeros(100,dtype=int))#hyperarameter tunning
print(np.zeros(100,dtype=float))#hyperarameter tunning
print(np.zeros(100,dtype=complex))#hyperarameter tunning
print(np.zeros(100,dtype=bool))#hyperarameter tunning
print(np.zeros(100,dtype=str))#hyperarameter tunning

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+

In [15]:
print(np.zeros((2,2)))#2 rows and 2 columns, that means 2x2 matrix
print()
print(np.zeros((5,20)))#5 rows and 20 columns, that means 5x20 matrix
print()
print(np.zeros((20,20),dtype=int))

[[0. 0.]
 [0. 0.]]

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 

In [16]:
matrix=(10,2)
array=np.zeros(matrix,dtype=int)
print(array)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [17]:
#ones(): it is used to get the arrays filled with 1's.
#by default it returns the array with float values, we need to perform hyer parameter tunning for different datatypes  
print(np.ones(4))
print(np.ones(4,dtype=int))
print(np.ones((6,6),dtype=int))

[1. 1. 1. 1.]
[1 1 1 1]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [18]:
np.two(4)#we have only 0's and 1's

AttributeError: module 'numpy' has no attribute 'two'

In [19]:
import numpy as np
#from numpy import * ==> by using this we can directly call without np (i.e like -> arange(3)/zeros(4)...etc)
#whenever we use from numpy import *, all the functions of numpy library will imported. 
#so that's the reason we can able to use all the functions directly with the function names.
np.arange(4)

array([0, 1, 2, 3])

In [20]:
#random.rand(): it is used to get an array with random numbers.
#example

print(np.random.rand(4))#give an array of 4 random numbers
print('===========================')
print(np.random.rand(4,5))#random numbers with 4 rows and 5 columns

[0.51161539 0.97596198 0.00765227 0.7968062 ]
[[0.55741197 0.22978456 0.07153014 0.26718352 0.426236  ]
 [0.03371023 0.55949461 0.43672778 0.88588155 0.47212365]
 [0.84001427 0.719826   0.87199515 0.04799314 0.59349096]
 [0.212232   0.73350832 0.90207154 0.53336673 0.82519371]]


In [22]:
#random.randint(): it is used to generate random numbers with given interval.
#example
a=np.random.randint(1000,9999)
print(a)
print(np.random.randint(10,20,5))#returns 5 numbers between 10 to 19
print(np.random.randint(1))#returns always 0
print(np.zeros(2,dtype=int))#write a numpy code that gives output always zero
print(np.random.randint(10,20,(5,6)))

print(np.random.randint(100,200,(5,5)))
print("=====")
print(np.random.rand(5,10))

2959
[15 16 10 12 19]
0
[0 0]
[[12 18 17 13 17 17]
 [18 19 19 11 12 19]
 [12 12 14 18 15 12]
 [18 19 11 15 18 16]
 [14 18 17 15 18 18]]
[[157 160 167 157 148]
 [104 114 121 114 130]
 [164 195 114 113 178]
 [116 105 174 105 157]
 [167 150 147 140 183]]
=====
[[0.71451719 0.58309823 0.53493778 0.09956156 0.62547665 0.87707565
  0.22832558 0.96340911 0.80930316 0.67594427]
 [0.22636979 0.14544558 0.69230526 0.30973389 0.04371543 0.50670531
  0.00199872 0.47863    0.61086054 0.6026838 ]
 [0.46347744 0.35439641 0.42827091 0.28421091 0.74165405 0.990436
  0.693213   0.36430113 0.05423209 0.38047555]
 [0.57958986 0.82887308 0.14608101 0.08192653 0.77330846 0.04892877
  0.71934074 0.38515267 0.01526773 0.04509478]
 [0.65071561 0.09985698 0.62241638 0.25972111 0.65846593 0.55998782
  0.6442733  0.97232687 0.36166685 0.28199818]]


In [23]:
#matrix slicing
a=np.random.randint(1,5,(6,5))
print(a)
print('slicing in matrix')
print(a[:])#return all
print('=======================')

[[2 4 4 2 3]
 [1 3 3 2 2]
 [2 2 2 1 1]
 [4 2 2 1 2]
 [2 4 1 4 2]
 [2 2 4 4 1]]
slicing in matrix
[[2 4 4 2 3]
 [1 3 3 2 2]
 [2 2 2 1 1]
 [4 2 2 1 2]
 [2 4 1 4 2]
 [2 2 4 4 1]]


In [24]:
print(a)
print('=====================')
print(a[0:2])
print('=====================')
print(a[2:-2])
print('=============')
print()

[[2 4 4 2 3]
 [1 3 3 2 2]
 [2 2 2 1 1]
 [4 2 2 1 2]
 [2 4 1 4 2]
 [2 2 4 4 1]]
[[2 4 4 2 3]
 [1 3 3 2 2]]
[[2 2 2 1 1]
 [4 2 2 1 2]]

